# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

inhibit_all_warnings!

target 'LCEiTimerDiary' do
    pod 'YTKNetwork'
    pod 'Mantle'
    pod 'MagicalRecord'
    pod 'libextobjc'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'LCProgressHUD'
    pod 'VTMagic'
    pod 'SensorsAnalyticsSDK'

  target 'LCEiTimerDiaryTests' do
    inherit! :search_paths
    pod 'Expecta'
  end

  target 'LCEiTimerDiaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
